<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup Label="Test dependencies">
    <PackageReference Include="JetBrains.Annotations"/>
    <PackageReference Include="TUnit"/>
  </ItemGroup>

  <ItemGroup Label="Project under test">
    <ProjectReference Include="..\..\DevilDaggersInfo.Core.Spawnset\DevilDaggersInfo.Core.Spawnset.csproj"/>
  </ItemGroup>

  <ItemGroup Label="Test resources">
    <None Update="Resources\**\*">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
