<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003" ToolsVersion="Current">

	<PropertyGroup>
		<ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
	</PropertyGroup>

	<ItemGroup Label="Runtime dependencies">
		<PackageVersion Include="SixLabors.ImageSharp" Version="3.1.12"/>
	</ItemGroup>

	<ItemGroup Label="Test dependencies">
		<PackageVersion Include="coverlet.collector" Version="6.0.4"/>
		<PackageVersion Include="JetBrains.Annotations" Version="2024.3.0"/>
		<PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.13.0"/>
		<PackageVersion Include="MSTest.TestAdapter" Version="3.7.3"/>
		<PackageVersion Include="MSTest.TestFramework" Version="3.7.3"/>
	</ItemGroup>

	<ItemGroup Label="Static code analysis">
		<GlobalPackageReference Include="Nullable.Extended.Analyzer" Version="1.15.6581"/>
		<GlobalPackageReference Include="Roslynator.Analyzers" Version="4.16.0"/>
		<GlobalPackageReference Include="SonarAnalyzer.CSharp" Version="10.32.0.713"/>
		<GlobalPackageReference Include="StyleCop.Analyzers" Version="1.2.0-beta.556"/>
	</ItemGroup>

</Project>
