<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup Label="Test dependencies">
    <PackageReference Include="TUnit"/>
  </ItemGroup>

  <ItemGroup Label="Project under test">
    <ProjectReference Include="..\..\DevilDaggersInfo.Core.Common\DevilDaggersInfo.Core.Common.csproj"/>
  </ItemGroup>

</Project>
